version: "3.7"

services:
  web:
    build: ./sport_api
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./sport_api/:/usr/src/sport_api/
    ports:
      - 8888:8888
    env_file:
      - ./.env.dev
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    #volumes:
    #  - ./data-db:/data/db
    ports:
      - 27017:27017

volumes:
  postgres_data:
