version: "3.8"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/backup:/data/backup
    ports:
      - 27017:27017
    restart: always

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - mongo

  #volumes:
  #  postgres_data:
