version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.9
        environment: # environment variables for primary container
          TEST_DATABASE_URL: localhost:27017
          PIPENV_VENV_IN_PROJECT: true

      - image: circleci/mongo:latest
        port: 27017:27017
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run: sudo rm -rf /home/circleci/project/

      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pip install -r requirements.txt

       - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"

      - run:
          command: (coverage run manage.py test football)
      - checkout
      
      - run:
          name: Running tests
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-reports/
          destination: python_app