version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.9
        environment: # environment variables for primary container
          TEST_DATABASE_URL: mongo://root@localhost/circle_test
          PIPENV_VENV_IN_PROJECT: true

      - image: circleci/mongo:latest
        port: 27017:27017
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      
      # - restore_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pip install -r requirements.txt
      # - save_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #     paths:
      #       - "venv"

      - setup_remote_docker
      # - run:
          # name: waiting for mongo
          # command: dockerize -wait tcp://localhost:27017 -timeout 1m

      - checkout
      
      - run:
          name: Running tests
          command: |
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app